#pragma once

typedef enum Attribute {
    Attribute_FastCasting = 0,
    Attribute_IllusionMagic = 1,
    Attribute_DominationMagic = 2,
    Attribute_InspirationMagic = 3,
    Attribute_BloodMagic = 4,
    Attribute_DeathMagic = 5,
    Attribute_SoulReaping = 6,
    Attribute_Curses = 7,
    Attribute_AirMagic = 8,
    Attribute_EarthMagic = 9,
    Attribute_FireMagic = 10,
    Attribute_WaterMagic = 11,
    Attribute_EnergyStorage = 12,
    Attribute_HealingPrayers = 13,
    Attribute_SmitingPrayers = 14,
    Attribute_ProtectionPrayers = 15,
    Attribute_DivineFavor = 16,
    Attribute_Strength = 17,
    Attribute_AxeMastery = 18,
    Attribute_HammerMastery = 19,
    Attribute_Swordsmanship = 20,
    Attribute_Tactics = 21,
    Attribute_BeastMastery = 22,
    Attribute_Expertise = 23,
    Attribute_WildernessSurvival = 24,
    Attribute_Marksmanship = 25,
    Attribute_DaggerMastery = 26,
    Attribute_DeadlyArts = 27,
    Attribute_ShadowArts = 28,
    Attribute_Communing = 29,
    Attribute_RestorationMagic = 30,
    Attribute_ChannelingMagic = 31,
    Attribute_CriticalStrikes = 32,
    Attribute_SpawningPower = 33,
    Attribute_SpearMastery = 34,
    Attribute_Command = 35,
    Attribute_Motivation = 36,
    Attribute_Leadership = 37,
    Attribute_ScytheMastery = 38,
    Attribute_WindPrayers = 39,
    Attribute_EarthPrayers = 40,
    Attribute_Mysticism = 41,

    Attribute_Count,
} Attribute;
