#pragma once

#define MapIdDefs \
    X(MapId_None, 0) \
    X(MapId_GladiatorsArena, 1) \
    X(MapId_DEVTestArena1v1, 2) \
    X(MapId_TestMap, 3) \
    X(MapId_WarriorsIsleOutpost, 4) \
    X(MapId_HuntersIsleOutpost, 5) \
    X(MapId_WizardsIsleOutpost, 6) \
    X(MapId_WarriorsIsle, 7) \
    X(MapId_HuntersIsle, 8) \
    X(MapId_WizardsIsle, 9) \
    X(MapId_BloodstoneFen, 10) \
    X(MapId_TheWilds, 11) \
    X(MapId_AuroraGlade, 12) \
    X(MapId_DiessaLowlands, 13) \
    X(MapId_GatesOfKryta, 14) \
    X(MapId_DAlessioSeaboard, 15) \
    X(MapId_DivinityCoast, 16) \
    X(MapId_TalmarkWilderness, 17) \
    X(MapId_TheBlackCurtain, 18) \
    X(MapId_SanctumCay, 19) \
    X(MapId_DroknarsForgeOutpost, 20) \
    X(MapId_TheFrostGate, 21) \
    X(MapId_IceCavesOfSorrow, 22) \
    X(MapId_ThunderheadKeep, 23) \
    X(MapId_IronMinesOfMoladune, 24) \
    X(MapId_BorlisPass, 25) \
    X(MapId_TalusChute, 26) \
    X(MapId_GriffonsMouth, 27) \
    X(MapId_TheGreatNorthernWall, 28) \
    X(MapId_FortRanik, 29) \
    X(MapId_RuinsOfSurmia, 30) \
    X(MapId_XaquangSkyway, 31) \
    X(MapId_NolaniAcademy, 32) \
    X(MapId_OldAscalon, 33) \
    X(MapId_TheFissureOfWoe, 34) \
    X(MapId_EmberLightCampOutpost, 35) \
    X(MapId_GrendichCourthouseOutpost, 36) \
    X(MapId_GlintsChallengeMission, 37) \
    X(MapId_AuguryRockOutpost, 38) \
    X(MapId_SardelacSanitariumOutpost, 39) \
    X(MapId_PikenSquareOutpost, 40) \
    X(MapId_SageLands, 41) \
    X(MapId_MamnoonLagoon, 42) \
    X(MapId_Silverwood, 43) \
    X(MapId_EttinsBack, 44) \
    X(MapId_ReedBog, 45) \
    X(MapId_TheFalls, 46) \
    X(MapId_DryTop, 47) \
    X(MapId_TangleRoot, 48) \
    X(MapId_HengeOfDenraviOutpost, 49) \
    X(MapType_50, 50) \
    X(MapId_SenjisCornerOutpost, 51) \
    X(MapId_BurningIsleOutpost, 52) \
    X(MapId_TearsOfTheFallen, 53) \
    X(MapId_ScoundrelsRise, 54) \
    X(MapId_LionsArchOutpost, 55) \
    X(MapId_CursedLands, 56) \
    X(MapId_BergenHotSpringsOutpost, 57) \
    X(MapId_NorthKrytaProvince, 58) \
    X(MapId_NeboTerrace, 59) \
    X(MapId_MajestysRest, 60) \
    X(MapId_TwinSerpentLakes, 61) \
    X(MapId_WatchtowerCoast, 62) \
    X(MapId_StingrayStrand, 63) \
    X(MapId_KessexPeak, 64) \
    X(MapId_DAlessioArenaMission, 65) \
    X(MapType_66, 66) \
    X(MapId_BurningIsle, 67) \
    X(MapId_FrozenIsle, 68) \
    X(MapId_NomadsIsle, 69) \
    X(MapId_DruidsIsle, 70) \
    X(MapId_IsleOfTheDeadGuildHall, 71) \
    X(MapId_TheUnderworld, 72) \
    X(MapId_RiversideProvince, 73) \
    X(MapType_74, 74) \
    X(MapId_TheHallOfHeroesArenaMission, 75) \
    X(MapId_BrokenTowerMission, 76) \
    X(MapId_HouseZuHeltzerOutpost, 77) \
    X(MapId_TheCourtyardArenaMission, 78) \
    X(MapId_UnholyTemplesMission, 79) \
    X(MapId_BurialMoundsMission, 80) \
    X(MapId_AscalonCityOutpost, 81) \
    X(MapId_TombOfThePrimevalKings, 82) \
    X(MapId_TheVaultMission, 83) \
    X(MapId_TheUnderworldArenaMission, 84) \
    X(MapId_AscalonArena, 85) \
    X(MapId_SacredTemplesMission, 86) \
    X(MapId_Icedome, 87) \
    X(MapId_IronHorseMine, 88) \
    X(MapId_AnvilRock, 89) \
    X(MapId_LornarsPass, 90) \
    X(MapId_SnakeDance, 91) \
    X(MapId_TascasDemise, 92) \
    X(MapId_SpearheadPeak, 93) \
    X(MapId_IceFloe, 94) \
    X(MapId_WitmansFolly, 95) \
    X(MapId_MineralSprings, 96) \
    X(MapId_DreadnoughtsDrift, 97) \
    X(MapId_FrozenForest, 98) \
    X(MapId_TravelersVale, 99) \
    X(MapId_DeldrimorBowl, 100) \
    X(MapId_RegentValley, 101) \
    X(MapId_TheBreach, 102) \
    X(MapId_AscalonFoothills, 103) \
    X(MapId_PockmarkFlats, 104) \
    X(MapId_DragonsGullet, 105) \
    X(MapId_FlameTempleCorridor, 106) \
    X(MapId_EasternFrontier, 107) \
    X(MapId_TheScar, 108) \
    X(MapId_TheAmnoonOasisOutpost, 109) \
    X(MapId_DivinersAscent, 110) \
    X(MapId_VultureDrifts, 111) \
    X(MapId_TheAridSea, 112) \
    X(MapId_ProphetsPath, 113) \
    X(MapId_SaltFlats, 114) \
    X(MapId_SkywardReach, 115) \
    X(MapId_DunesOfDespair, 116) \
    X(MapId_ThirstyRiver, 117) \
    X(MapId_ElonaReach, 118) \
    X(MapId_AuguryRockMission, 119) \
    X(MapId_TheDragonsLair, 120) \
    X(MapId_PerditionRock, 121) \
    X(MapId_RingOfFire, 122) \
    X(MapId_AbaddonsMouth, 123) \
    X(MapId_HellsPrecipice, 124) \
    X(MapId_TitansTears, 125) \
    X(MapId_GoldenGatesMission, 126) \
    X(MapId_ScarredEarth2, 127) \
    X(MapId_TheEternalGrove, 128) \
    X(MapId_LutgardisConservatoryOutpost, 129) \
    X(MapId_VasburgArmoryOutpost, 130) \
    X(MapId_SerenityTempleOutpost, 131) \
    X(MapId_IceToothCaveOutpost, 132) \
    X(MapId_BeaconsPerchOutpost, 133) \
    X(MapId_YaksBendOutpost, 134) \
    X(MapId_FrontierGateOutpost, 135) \
    X(MapId_BeetletunOutpost, 136) \
    X(MapId_FishermensHavenOutpost, 137) \
    X(MapId_TempleOfTheAges, 138) \
    X(MapId_VentarisRefugeOutpost, 139) \
    X(MapId_DruidsOverlookOutpost, 140) \
    X(MapId_MaguumaStadeOutpost, 141) \
    X(MapId_QuarrelFallsOutpost, 142) \
    X(MapType_143, 143) \
    X(MapId_GyalaHatchery, 144) \
    X(MapId_TheCatacombs, 145) \
    X(MapId_LakesideCounty, 146) \
    X(MapId_TheNorthlands, 147) \
    X(MapId_AscalonCityPreSearing, 148) \
    X(MapId_AscalonAcademy, 149) \
    X(MapId_AscalonAcademyPvPBattleMission, 150) \
    X(MapId_AscalonAcademyUnk, 151) \
    X(MapId_HeroesAudienceOutpost, 152) \
    X(MapId_SeekersPassageOutpost, 153) \
    X(MapId_DestinysGorgeOutpost, 154) \
    X(MapId_CampRankorOutpost, 155) \
    X(MapId_TheGraniteCitadelOutpost, 156) \
    X(MapId_MarhansGrottoOutpost, 157) \
    X(MapId_PortSledgeOutpost, 158) \
    X(MapId_CopperhammerMinesOutpost, 159) \
    X(MapId_GreenHillsCounty, 160) \
    X(MapId_WizardsFolly, 161) \
    X(MapId_RegentValleyPreSearing, 162) \
    X(MapId_TheBarradinEstateOutpost, 163) \
    X(MapId_AshfordAbbeyOutpost, 164) \
    X(MapId_FoiblesFairOutpost, 165) \
    X(MapId_FortRanikPreSearingOutpost, 166) \
    X(MapId_BurningIsleMission, 167) \
    X(MapId_DruidsIsleMission, 168) \
    X(MapType_169, 169) \
    X(MapId_FrozenIsleMission, 170) \
    X(MapId_WarriorsIsleMission, 171) \
    X(MapId_HuntersIsleMission, 172) \
    X(MapId_WizardsIsleMission, 173) \
    X(MapId_NomadsIsleMission, 174) \
    X(MapId_IsleOfTheDeadGuildHallMission, 175) \
    X(MapId_FrozenIsleOutpost, 176) \
    X(MapId_NomadsIsleOutpost, 177) \
    X(MapId_DruidsIsleOutpost, 178) \
    X(MapId_IsleOfTheDeadGuildHallOutpost, 179) \
    X(MapId_FortKogaMission, 180) \
    X(MapId_ShiverpeakArena, 181) \
    X(MapId_AmnoonArenaMission, 182) \
    X(MapId_DeldrimorArenaMission, 183) \
    X(MapId_TheCragMission, 184) \
    X(MapType_185, 185) \
    X(MapType_186, 186) \
    X(MapType_187, 187) \
    X(MapId_RandomArenasOutpost, 188) \
    X(MapId_TeamArenasOutpost, 189) \
    X(MapId_SorrowsFurnace, 190) \
    X(MapId_GrenthsFootprint, 191) \
    X(MapType_192, 192) \
    X(MapId_CavalonOutpost, 193) \
    X(MapId_KainengCenterOutpost, 194) \
    X(MapId_DrazachThicket, 195) \
    X(MapId_JayaBluffs, 196) \
    X(MapId_ShenzunTunnels, 197) \
    X(MapId_Archipelagos, 198) \
    X(MapId_MaishangHills, 199) \
    X(MapId_MountQinkai, 200) \
    X(MapId_MelandrusHope, 201) \
    X(MapId_RheasCrater, 202) \
    X(MapId_SilentSurf, 203) \
    X(MapId_UnwakingWatersMission, 204) \
    X(MapId_MorostavTrail, 205) \
    X(MapId_DeldrimorWarCampOutpost, 206) \
    X(MapType_207, 207) \
    X(MapId_HeroesCryptMission, 208) \
    X(MapId_MourningVeilFalls, 209) \
    X(MapId_Ferndale, 210) \
    X(MapId_PongmeiValley, 211) \
    X(MapId_MonasteryOverlook1, 212) \
    X(MapId_ZenDaijunOutpostMission, 213) \
    X(MapId_MinisterChosEstateOutpostMission, 214) \
    X(MapId_VizunahSquareMission, 215) \
    X(MapId_NahpuiQuarterOutpostMission, 216) \
    X(MapId_TahnnakaiTempleOutpostMission, 217) \
    X(MapId_ArborstoneOutpostMission, 218) \
    X(MapId_BoreasSeabedOutpostMission, 219) \
    X(MapId_SunjiangDistrictOutpostMission, 220) \
    X(MapId_FortAspenwoodMission, 221) \
    X(MapId_TheEternalGroveOutpostMission, 222) \
    X(MapId_TheJadeQuarryMission, 223) \
    X(MapId_GyalaHatcheryOutpostMission, 224) \
    X(MapId_RaisuPalaceOutpostMission, 225) \
    X(MapId_ImperialSanctumOutpostMission, 226) \
    X(MapId_UnwakingWaters, 227) \
    X(MapId_GrenzFrontierMission, 228) \
    X(MapType_229, 229) \
    X(MapId_AmatzBasin, 230) \
    X(MapType_231, 231) \
    X(MapId_ShadowsPassage, 232) \
    X(MapId_RaisuPalace, 233) \
    X(MapId_TheAuriosMines, 234) \
    X(MapId_PanjiangPeninsula, 235) \
    X(MapId_KinyaProvince, 236) \
    X(MapId_HaijuLagoon, 237) \
    X(MapId_SunquaVale, 238) \
    X(MapId_WajjunBazaar, 239) \
    X(MapId_BukdekByway, 240) \
    X(MapId_TheUndercity, 241) \
    X(MapId_ShingJeaMonasteryOutpost, 242) \
    X(MapId_ShingJeaArena, 243) \
    X(MapId_ArborstoneExplorable, 244) \
    X(MapId_MinisterChosEstateExplorable, 245) \
    X(MapId_ZenDaijunExplorable, 246) \
    X(MapId_BoreasSeabedExplorable, 247) \
    X(MapId_GreatTempleOfBalthazarOutpost, 248) \
    X(MapId_TsumeiVillageOutpost, 249) \
    X(MapId_SeitungHarborOutpost, 250) \
    X(MapId_RanMusuGardensOutpost, 251) \
    X(MapId_LinnokCourtyard, 252) \
    X(MapId_DwaynaVsGrenth, 253) \
    X(MapType_254, 254) \
    X(MapType_255, 255) \
    X(MapId_SunjiangDistrictExplorable, 256) \
    X(MapType_257, 257) \
    X(MapType_258, 258) \
    X(MapType_259, 259) \
    X(MapType_260, 260) \
    X(MapType_261, 261) \
    X(MapType_262, 262) \
    X(MapType_263, 263) \
    X(MapType_264, 264) \
    X(MapId_NahpuiQuarterExplorable, 265) \
    X(MapId_UrgozsWarren, 266) \
    X(MapType_267, 267) \
    X(MapType_268, 268) \
    X(MapId_TahnnakaiTempleExplorable, 269) \
    X(MapType_270, 270) \
    X(MapType_271, 271) \
    X(MapId_AltrummRuins, 272) \
    X(MapId_ZosShivrosChannel, 273) \
    X(MapId_DragonsThroat, 274) \
    X(MapId_IsleOfWeepingStoneOutpost, 275) \
    X(MapId_IsleOfJadeOutpost, 276) \
    X(MapId_HarvestTempleOutpost, 277) \
    X(MapId_BreakerHollowOutpost, 278) \
    X(MapId_LeviathanPitsOutpost, 279) \
    X(MapId_IsleOfTheNameless, 280) \
    X(MapId_ZaishenChallengeOutpost, 281) \
    X(MapId_ZaishenEliteOutpost, 282) \
    X(MapId_MaatuKeepOutpost, 283) \
    X(MapId_ZinKuCorridorOutpost, 284) \
    X(MapId_MonasteryOverlook2, 285) \
    X(MapId_BrauerAcademyOutpost, 286) \
    X(MapId_DurheimArchivesOutpost, 287) \
    X(MapId_BaiPaasuReachOutpost, 288) \
    X(MapId_SeafarersRestOutpost, 289) \
    X(MapId_BejunkanPier, 290) \
    X(MapId_VizunahSquareLocalQuarterOutpost, 291) \
    X(MapId_VizunahSquareForeignQuarterOutpost, 292) \
    X(MapId_FortAspenwoodLuxonOutpost, 293) \
    X(MapId_FortAspenwoodKurzickOutpost, 294) \
    X(MapId_TheJadeQuarryLuxonOutpost, 295) \
    X(MapId_TheJadeQuarryKurzickOutpost, 296) \
    X(MapId_UnwakingWatersLuxonOutpost, 297) \
    X(MapId_UnwakingWatersKurzickOutpost, 298) \
    X(MapType_299, 299) \
    X(MapId_EtnaranKeysMission, 300) \
    X(MapId_RaisuPavilion, 301) \
    X(MapId_KainengDocks, 302) \
    X(MapId_TheMarketplaceOutpost, 303) \
    X(MapType_304, 304) \
    X(MapType_305, 305) \
    X(MapType_306, 306) \
    X(MapId_TheDeep, 307) \
    X(MapId_AscalonArenaMission, 308) \
    X(MapId_AnnihilationMission, 309) \
    X(MapId_KillCountTrainingMission, 310) \
    X(MapId_PriestAnnihilationTraining, 311) \
    X(MapId_ObeliskAnnihilationTrainingMission, 312) \
    X(MapId_SaoshangTrail, 313) \
    X(MapId_ShiverpeakArenaMission, 314) \
    X(MapType_315, 315) \
    X(MapType_316, 316) \
    X(MapType_317, 317) \
    X(MapId_DAlessioArenaMission3, 318) \
    X(MapId_AmnoonArenaMission3, 319) \
    X(MapId_FortKogaMission3, 320) \
    X(MapId_HeroesCryptMission3, 321) \
    X(MapId_ShiverpeakArenaMission3, 322) \
    X(MapType_323, 323) \
    X(MapType_324, 324) \
    X(MapType_325, 325) \
    X(MapType_326, 326) \
    X(MapType_327, 327) \
    X(MapId_SaltsprayBeachLuxonOutpost, 328) \
    X(MapId_SaltsprayBeachKurzickOutpost, 329) \
    X(MapId_HeroesAscentOutpost, 330) \
    X(MapId_GrenzFrontierLuxonOutpost, 331) \
    X(MapId_GrenzFrontierKurzickOutpost, 332) \
    X(MapId_TheAncestralLandsLuxonOutpost, 333) \
    X(MapId_TheAncestralLandsKurzickOutpost, 334) \
    X(MapId_EtnaranKeysLuxonOutpost, 335) \
    X(MapId_EtnaranKeysKurzickOutpost, 336) \
    X(MapId_KaanaiCanyonLuxonOutpost, 337) \
    X(MapId_KaanaiCanyonKurzickOutpost, 338) \
    X(MapId_DAlessioArenaMission2, 339) \
    X(MapId_AmnoonArenaMission2, 340) \
    X(MapId_FortKogaMission2, 341) \
    X(MapId_HeroesCryptMission2, 342) \
    X(MapId_ShiverpeakArenaMission2, 343) \
    X(MapId_TheHallOfHeroes, 344) \
    X(MapId_TheCourtyard, 345) \
    X(MapId_ScarredEarth, 346) \
    X(MapId_TheUnderworldPvP, 347) \
    X(MapId_TanglewoodCopseOutpost, 348) \
    X(MapId_SaintAnjekasShrineOutpost, 349) \
    X(MapId_EredonTerraceOutpost, 350) \
    X(MapId_DivinePath, 351) \
    X(MapId_BrawlersPitMission, 352) \
    X(MapId_PetrifiedArenaMission, 353) \
    X(MapId_SeabedArenaMission, 354) \
    X(MapId_IsleOfWeepingStoneMission, 355) \
    X(MapId_IsleOfJadeMission, 356) \
    X(MapId_ImperialIsleMission, 357) \
    X(MapId_IsleOfMeditationMission, 358) \
    X(MapId_ImperialIsleOutpost, 359) \
    X(MapId_IsleOfMeditationOutpost, 360) \
    X(MapId_IsleOfWeepingStone, 361) \
    X(MapId_IsleOfJade, 362) \
    X(MapId_ImperialIsle, 363) \
    X(MapId_IsleOfMeditation, 364) \
    X(MapType_365, 365) \
    X(MapId_ShingJeaArenaMission, 366) \
    X(MapType_367, 367) \
    X(MapId_DragonArena, 368) \
    X(MapId_JahaiBluffs, 369) \
    X(MapId_KamadanMission, 370) \
    X(MapId_MargaCoast, 371) \
    X(MapId_FahranurMission, 372) \
    X(MapId_SunwardMarches, 373) \
    X(MapType_374, 374) \
    X(MapId_BarbarousShore, 375) \
    X(MapId_CampHojanuOutpost, 376) \
    X(MapId_BahdokCaverns, 377) \
    X(MapId_WehhanTerracesOutpost, 378) \
    X(MapId_DejarinEstate, 379) \
    X(MapId_ArkjokWard, 380) \
    X(MapId_YohlonHavenOutpost, 381) \
    X(MapId_GandaraTheMoonFortress, 382) \
    X(MapType_383, 383) \
    X(MapId_TheFloodplainOfMahnkelon, 384) \
    X(MapId_LionsArchSunspearsInKryta, 385) \
    X(MapId_TuraisProcession, 386) \
    X(MapId_SunspearSanctuaryOutpost, 387) \
    X(MapId_AspenwoodGateKurzickOutpost, 388) \
    X(MapId_AspenwoodGateLuxonOutpost, 389) \
    X(MapId_JadeFlatsKurzickOutpost, 390) \
    X(MapId_JadeFlatsLuxonOutpost, 391) \
    X(MapId_YatendiCanyons, 392) \
    X(MapId_ChantryOfSecretsOutpost, 393) \
    X(MapId_GardenOfSeborhin, 394) \
    X(MapId_HoldingsOfChokhin, 395) \
    X(MapId_MihanuTownshipOutpost, 396) \
    X(MapId_VehjinMines, 397) \
    X(MapId_BasaltGrottoOutpost, 398) \
    X(MapId_ForumHighlands, 399) \
    X(MapId_KainengCenterSunspearsInCantha, 400) \
    X(MapType_401, 401) \
    X(MapId_ResplendentMakuun, 402) \
    X(MapId_HonurHillOutpost, 403) \
    X(MapId_WildernessOfBahdza, 404) \
    X(MapType_405, 405) \
    X(MapId_VehtendiValley, 406) \
    X(MapId_YahnurMarketOutpost, 407) \
    X(MapType_408, 408) \
    X(MapType_409, 409) \
    X(MapType_410, 410) \
    X(MapType_411, 411) \
    X(MapType_412, 412) \
    X(MapId_TheHiddenCityOfAhdashim, 413) \
    X(MapId_TheKodashBazaarOutpost, 414) \
    X(MapId_LionsGate, 415) \
    X(MapType_416, 416) \
    X(MapType_417, 417) \
    X(MapType_418, 418) \
    X(MapId_TheMirrorOfLyss, 419) \
    X(MapId_SecureTheRefuge, 420) \
    X(MapId_VentaCemetery, 421) \
    X(MapId_KamadanJewelOfIstanExplorable, 422) \
    X(MapId_TheTribunal, 423) \
    X(MapId_KodonurCrossroads, 424) \
    X(MapId_RilohnRefuge, 425) \
    X(MapId_PogahnPassage, 426) \
    X(MapId_ModdokCrevice, 427) \
    X(MapId_TiharkOrchard, 428) \
    X(MapId_Consulate, 429) \
    X(MapId_PlainsOfJarin, 430) \
    X(MapId_SunspearGreatHallOutpost, 431) \
    X(MapId_CliffsOfDohjok, 432) \
    X(MapId_DzagonurBastion, 433) \
    X(MapId_DashaVestibule, 434) \
    X(MapId_GrandCourtOfSebelkeh, 435) \
    X(MapId_CommandPost, 436) \
    X(MapId_JokosDomain, 437) \
    X(MapId_BonePalaceOutpost, 438) \
    X(MapId_TheRupturedHeart, 439) \
    X(MapId_TheMouthOfTormentOutpost, 440) \
    X(MapId_TheShatteredRavines, 441) \
    X(MapId_LairOfTheForgottenOutpost, 442) \
    X(MapId_PoisonedOutcrops, 443) \
    X(MapId_TheSulfurousWastes, 444) \
    X(MapId_TheEbonyCitadelOfMallyxMission, 445) \
    X(MapId_TheAlkaliPan, 446) \
    X(MapId_ALandOfHeroes, 447) \
    X(MapId_CrystalOverlook, 448) \
    X(MapId_KamadanJewelOfIstanOutpost, 449) \
    X(MapId_GateOfTormentOutpost, 450) \
    X(MapType_451, 451) \
    X(MapType_452, 452) \
    X(MapType_453, 453) \
    X(MapType_454, 454) \
    X(MapId_NightfallenGarden, 455) \
    X(MapId_ChurrhirFields, 456) \
    X(MapId_BeknurHarborOutpost, 457) \
    X(MapType_458, 458) \
    X(MapType_459, 459) \
    X(MapType_460, 460) \
    X(MapId_TheUnderworld2, 461) \
    X(MapId_HeartOfAbaddon, 462) \
    X(MapId_TheUnderworld3, 463) \
    X(MapId_NightfallenCoast, 464) \
    X(MapId_NightfallenJahai, 465) \
    X(MapId_DepthsOfMadness, 466) \
    X(MapId_RollerbeetleRacing, 467) \
    X(MapId_DomainOfFear, 468) \
    X(MapId_GateOfFearOutpost, 469) \
    X(MapId_DomainOfPain, 470) \
    X(MapId_BloodstoneFenQuest, 471) \
    X(MapId_DomainOfSecrets, 472) \
    X(MapId_GateOfSecretsOutpost, 473) \
    X(MapId_DomainOfAnguish, 474) \
    X(MapId_OozePitMission, 475) \
    X(MapId_JennursHorde, 476) \
    X(MapId_NunduBay, 477) \
    X(MapId_GateOfDesolation, 478) \
    X(MapId_ChampionsDawnOutpost, 479) \
    X(MapId_RuinsOfMorah, 480) \
    X(MapId_FahranurTheFirstCity, 481) \
    X(MapId_BjoraMarches, 482) \
    X(MapId_ZehlonReach, 483) \
    X(MapId_LahtendaBog, 484) \
    X(MapId_ArborBay, 485) \
    X(MapId_IssnurIsles, 486) \
    X(MapId_BeknurHarbor, 487) \
    X(MapId_MehtaniKeys, 488) \
    X(MapId_KodlonuHamletOutpost, 489) \
    X(MapId_IslandOfShehkah, 490) \
    X(MapId_JokanurDiggings, 491) \
    X(MapId_BlacktideDen, 492) \
    X(MapId_ConsulateDocks, 493) \
    X(MapId_GateOfPain, 494) \
    X(MapId_GateOfMadness, 495) \
    X(MapId_AbaddonsGate, 496) \
    X(MapId_SunspearArena, 497) \
    X(MapType_498, 498) \
    X(MapId_IceCliffChasms, 499) \
    X(MapId_BokkaAmphitheatre, 500) \
    X(MapId_RivenEarth, 501) \
    X(MapId_TheAstralariumOutpost, 502) \
    X(MapId_ThroneOfSecrets, 503) \
    X(MapId_ChurranuIslandArenaMission, 504) \
    X(MapId_ShingJeaMonasteryMission, 505) \
    X(MapId_HaijuLagoonMission, 506) \
    X(MapId_JayaBluffsMission, 507) \
    X(MapId_SeitungHarborMission, 508) \
    X(MapId_TsumeiVillageMission, 509) \
    X(MapId_SeitungHarborMission2, 510) \
    X(MapId_TsumeiVillageMission2, 511) \
    X(MapId_MinisterChosEstateMission2, 512) \
    X(MapId_DrakkarLake, 513) \
    X(MapType_514, 514) \
    X(MapType_515, 515) \
    X(MapType_516, 516) \
    X(MapType_517, 517) \
    X(MapType_518, 518) \
    X(MapType_519, 519) \
    X(MapType_520, 520) \
    X(MapType_521, 521) \
    X(MapType_522, 522) \
    X(MapType_523, 523) \
    X(MapType_524, 524) \
    X(MapType_525, 525) \
    X(MapType_526, 526) \
    X(MapType_527, 527) \
    X(MapType_528, 528) \
    X(MapId_UnchartedIsleOutpost, 529) \
    X(MapId_IsleOfWurmsOutpost, 530) \
    X(MapId_UnchartedIsle, 531) \
    X(MapId_IsleOfWurms, 532) \
    X(MapId_UnchartedIsleMission, 533) \
    X(MapId_IsleOfWurmsMission, 534) \
    X(MapType_535, 535) \
    X(MapId_SunspearArenaMission, 536) \
    X(MapId_CorruptedIsleOutpost, 537) \
    X(MapId_IsleOfSolitudeOutpost, 538) \
    X(MapId_CorruptedIsle, 539) \
    X(MapId_IsleOfSolitude, 540) \
    X(MapId_CorruptedIsleMission, 541) \
    X(MapId_IsleOfSolitudeMission, 542) \
    X(MapId_SunDocks, 543) \
    X(MapId_ChahbekVillage, 544) \
    X(MapId_RemainsOfSahlahja, 545) \
    X(MapId_JagaMoraine, 546) \
    X(MapId_BombardmentMission, 547) \
    X(MapId_NorrhartDomains, 548) \
    X(MapId_HeroBattlesOutpost, 549) \
    X(MapId_TheBeachheadMission, 550) \
    X(MapId_TheCrossingMission, 551) \
    X(MapId_DesertSandsMission, 552) \
    X(MapId_VarajarFells, 553) \
    X(MapId_DajkahInlet, 554) \
    X(MapId_TheShadowNexus, 555) \
    X(MapType_556, 556) \
    X(MapType_557, 557) \
    X(MapId_SparkflySwamp, 558) \
    X(MapId_GateOfTheNightfallenLandsOutpost, 559) \
    X(MapId_CathedralOfFlamesLevel1, 560) \
    X(MapId_TheTroubledKeeper, 561) \
    X(MapType_562, 562) \
    X(MapType_563, 563) \
    X(MapType_564, 564) \
    X(MapType_565, 565) \
    X(MapId_VerdantCascades, 566) \
    X(MapId_CathedralOfFlamesLevel2, 567) \
    X(MapId_CathedralOfFlamesLevel3, 568) \
    X(MapId_MagusStones, 569) \
    X(MapId_CatacombsOfKathandraxLevel1, 570) \
    X(MapId_CatacombsOfKathandraxLevel2, 571) \
    X(MapId_AlcaziaTangle, 572) \
    X(MapId_RragarsMenagerieLevel1, 573) \
    X(MapId_RragarsMenagerieLevel2, 574) \
    X(MapId_RragarsMenagerieLevel3, 575) \
    X(MapId_OozePit, 576) \
    X(MapId_SlaversExileLevel1, 577) \
    X(MapId_OolasLabLevel1, 578) \
    X(MapId_OolasLabLevel2, 579) \
    X(MapId_OolasLabLevel3, 580) \
    X(MapId_ShardsOfOrrLevel1, 581) \
    X(MapId_ShardsOfOrrLevel2, 582) \
    X(MapId_ShardsOfOrrLevel3, 583) \
    X(MapId_ArachnisHauntLevel1, 584) \
    X(MapId_ArachnisHauntLevel2, 585) \
    X(MapType_586, 586) \
    X(MapType_587, 587) \
    X(MapType_588, 588) \
    X(MapType_589, 589) \
    X(MapType_590, 590) \
    X(MapType_591, 591) \
    X(MapType_592, 592) \
    X(MapId_FetidRiverMission, 593) \
    X(MapType_594, 594) \
    X(MapType_595, 595) \
    X(MapId_ForgottenShrinesMission, 596) \
    X(MapType_597, 597) \
    X(MapId_AntechamberMission, 598) \
    X(MapType_599, 599) \
    X(MapType_600, 600) \
    X(MapType_601, 601) \
    X(MapType_602, 602) \
    X(MapType_603, 603) \
    X(MapId_VloxenExcavationsLevel1, 604) \
    X(MapId_VloxenExcavationsLevel2, 605) \
    X(MapId_VloxenExcavationsLevel3, 606) \
    X(MapId_HeartOfTheShiverpeaksLevel1, 607) \
    X(MapId_HeartOfTheShiverpeaksLevel2, 608) \
    X(MapId_HeartOfTheShiverpeaksLevel3, 609) \
    X(MapType_610, 610) \
    X(MapType_611, 611) \
    X(MapId_BloodstoneCavesLevel1, 612) \
    X(MapId_BloodstoneCavesLevel2, 613) \
    X(MapId_BloodstoneCavesLevel3, 614) \
    X(MapId_BogrootGrowthsLevel1, 615) \
    X(MapId_BogrootGrowthsLevel2, 616) \
    X(MapId_RavensPointLevel1, 617) \
    X(MapId_RavensPointLevel2, 618) \
    X(MapId_RavensPointLevel3, 619) \
    X(MapId_SlaversExileLevel2, 620) \
    X(MapId_SlaversExileLevel3, 621) \
    X(MapId_SlaversExileLevel4, 622) \
    X(MapId_SlaversExileLevel5, 623) \
    X(MapId_VloxsFalls, 624) \
    X(MapId_BattledepthsLevel1, 625) \
    X(MapId_BattledepthsLevel2, 626) \
    X(MapId_BattledepthsLevel3, 627) \
    X(MapId_SepulchreOfDragrimmarLevel1, 628) \
    X(MapId_SepulchreOfDragrimmarLevel2, 629) \
    X(MapId_FrostmawsBurrowsLevel1, 630) \
    X(MapId_FrostmawsBurrowsLevel2, 631) \
    X(MapId_FrostmawsBurrowsLevel3, 632) \
    X(MapId_FrostmawsBurrowsLevel4, 633) \
    X(MapId_FrostmawsBurrowsLevel5, 634) \
    X(MapId_DarkrimeDelvesLevel1, 635) \
    X(MapId_DarkrimeDelvesLevel2, 636) \
    X(MapId_DarkrimeDelvesLevel3, 637) \
    X(MapId_GaddsEncampmentOutpost, 638) \
    X(MapId_UmbralGrottoOutpost, 639) \
    X(MapId_RataSumOutpost, 640) \
    X(MapId_TarnishedHavenOutpost, 641) \
    X(MapId_EyeOfTheNorthOutpost, 642) \
    X(MapId_SifhallaOutpost, 643) \
    X(MapId_GunnarsHoldOutpost, 644) \
    X(MapId_OlafsteadOutpost, 645) \
    X(MapId_HallOfMonuments, 646) \
    X(MapId_DaladaUplands, 647) \
    X(MapId_DoomloreShrineOutpost, 648) \
    X(MapId_GrothmarWardowns, 649) \
    X(MapId_LongeyesLedgeOutpost, 650) \
    X(MapId_SacnothValley, 651) \
    X(MapId_CentralTransferChamberOutpost, 652) \
    X(MapId_CurseOfTheNornbear, 653) \
    X(MapId_BloodWashesBlood, 654) \
    X(MapId_AGateTooFarLevel1, 655) \
    X(MapId_AGateTooFarLevel2, 656) \
    X(MapId_AGateTooFarLevel3, 657) \
    X(MapId_TheElusiveGolemancerLevel1, 658) \
    X(MapId_TheElusiveGolemancerLevel2, 659) \
    X(MapId_TheElusiveGolemancerLevel3, 660) \
    X(MapId_FindingTheBloodstoneLevel1, 661) \
    X(MapId_FindingTheBloodstoneLevel2, 662) \
    X(MapId_FindingTheBloodstoneLevel3, 663) \
    X(MapId_GeniusOperatedLivingEnchantedManifestation, 664) \
    X(MapId_AgainstTheCharr, 665) \
    X(MapId_WarbandOfBrothersLevel1, 666) \
    X(MapId_WarbandOfBrothersLevel2, 667) \
    X(MapId_WarbandOfBrothersLevel3, 668) \
    X(MapId_AssaultOnTheStronghold, 669) \
    X(MapId_DestructionsDepthsLevel1, 670) \
    X(MapId_DestructionsDepthsLevel2, 671) \
    X(MapId_DestructionsDepthsLevel3, 672) \
    X(MapId_ATimeForHeroes, 673) \
    X(MapId_WarbandTraining, 674) \
    X(MapId_BorealStationOutpost, 675) \
    X(MapId_CatacombsOfKathandraxLevel3, 676) \
    X(MapType_677, 677) \
    X(MapId_AttackOfTheNornbear, 678) \
    X(MapId_CinematicCaveNornCursed, 679) \
    X(MapId_CinematicSteppeInterrogation, 680) \
    X(MapId_CinematicInteriorResearch, 681) \
    X(MapId_CinematicEyeVisionA, 682) \
    X(MapId_CinematicEyeVisionB, 683) \
    X(MapId_CinematicEyeVisionC, 684) \
    X(MapId_CinematicEyeVisionD, 685) \
    X(MapId_PolymockColiseum, 686) \
    X(MapId_PolymockGlacier, 687) \
    X(MapId_PolymockCrossing, 688) \
    X(MapId_CinematicMountainResolution, 689) \
    X(MapId_ColdAsIce, 690) \
    X(MapId_BeneathLionsArch, 691) \
    X(MapId_TunnelsBelowCantha, 692) \
    X(MapId_CavernsBelowKamadan, 693) \
    X(MapId_CinematicMountainDwarfs, 694) \
    X(MapId_ServiceInDefenseOfTheEye, 695) \
    X(MapId_ManoANornO, 696) \
    X(MapId_ServicePracticeDummy, 697) \
    X(MapId_HeroTutorial, 698) \
    X(MapType_699, 699) \
    X(MapId_TheNornFightingTournament, 700) \
    X(MapId_SecretLairOfTheSnowmen, 701) \
    X(MapId_NornBrawlingChampionship, 702) \
    X(MapId_KilroysPunchoutTraining, 703) \
    X(MapId_FronisIrontoesLairMission, 704) \
    X(MapId_TheJusticiarsEnd, 705) \
    X(MapType_706, 706) \
    X(MapId_TheGreatNornAlemoot, 707) \
    X(MapId_VarajarFellsUnknown, 708) \
    X(MapType_709, 709) \
    X(MapId_Epilogue, 710) \
    X(MapId_InsidiousRemnants, 711) \
    X(MapType_712, 712) \
    X(MapType_713, 713) \
    X(MapType_714, 714) \
    X(MapType_715, 715) \
    X(MapType_716, 716) \
    X(MapId_AttackOnJalissCamp, 717) \
    X(MapType_718, 718) \
    X(MapType_719, 719) \
    X(MapType_720, 720) \
    X(MapId_CostumeBrawlOutpost, 721) \
    X(MapId_WhitefuryRapidsMission, 722) \
    X(MapId_KystenShoreMission, 723) \
    X(MapId_DeepwayRuinsMission, 724) \
    X(MapId_PlikkupWorksMission, 725) \
    X(MapId_KilroysPunchoutTournament, 726) \
    X(MapId_SpecialOpsFlameTempleCorridor, 727) \
    X(MapId_SpecialOpsDragonsGullet, 728) \
    X(MapId_SpecialOpsGrendichCourthouse, 729) \
    X(MapId_TheTenguAccords, 730) \
    X(MapId_TheBattleOfJahai, 731) \
    X(MapId_TheFlightNorth, 732) \
    X(MapId_TheRiseOfTheWhiteMantle, 733) \
    X(MapType_734, 734) \
    X(MapType_735, 735) \
    X(MapType_736, 736) \
    X(MapType_737, 737) \
    X(MapType_738, 738) \
    X(MapType_739, 739) \
    X(MapType_740, 740) \
    X(MapType_741, 741) \
    X(MapType_742, 742) \
    X(MapType_743, 743) \
    X(MapType_744, 744) \
    X(MapType_745, 745) \
    X(MapType_746, 746) \
    X(MapType_747, 747) \
    X(MapType_748, 748) \
    X(MapType_749, 749) \
    X(MapType_750, 750) \
    X(MapType_751, 751) \
    X(MapType_752, 752) \
    X(MapType_753, 753) \
    X(MapType_754, 754) \
    X(MapType_755, 755) \
    X(MapType_756, 756) \
    X(MapType_757, 757) \
    X(MapType_758, 758) \
    X(MapId_FindingTheBloodstoneMission, 759) \
    X(MapId_GeniusOperatedLivingEnchantedManifestationMission, 760) \
    X(MapId_AgainstTheCharrMission, 761) \
    X(MapId_WarbandOfBrothersMission, 762) \
    X(MapId_AssaultOnTheStrongholdMission, 763) \
    X(MapId_DestructionsDepthsMission, 764) \
    X(MapId_ATimeForHeroesMission, 765) \
    X(MapId_CurseOfTheNornbearMission, 766) \
    X(MapId_BloodWashesBloodMission, 767) \
    X(MapId_AGateTooFarMission, 768) \
    X(MapId_TheElusiveGolemancerMission, 769) \
    X(MapType_770, 770) \
    X(MapType_771, 771) \
    X(MapType_772, 772) \
    X(MapType_773, 773) \
    X(MapType_774, 774) \
    X(MapType_775, 775) \
    X(MapType_776, 776) \
    X(MapType_777, 777) \
    X(MapType_778, 778) \
    X(MapType_779, 779) \
    X(MapType_780, 780) \
    X(MapId_SecretLairOfTheSnowmen2, 781) \
    X(MapId_SecretLairOfTheSnowmen3, 782) \
    X(MapId_DroknarsForgeCinematic, 783) \
    X(MapId_IsleOfTheNamelessPvP, 784) \
    X(MapType_785, 785) \
    X(MapType_786, 786) \
    X(MapType_787, 787) \
    X(MapId_TempleOfTheAgesROX, 788) \
    X(MapId_WajjunBazaarPOX, 789) \
    X(MapId_BokkaAmphitheatreNOX, 790) \
    X(MapId_SecretUndergroundLair, 791) \
    X(MapId_GolemTutorialSimulation, 792) \
    X(MapId_SnowballDominance, 793) \
    X(MapId_ZaishenMenagerieGrounds, 794) \
    X(MapId_ZaishenMenagerieOutpost, 795) \
    X(MapId_CodexArenaOutpost, 796) \
    X(MapType_797, 797) \
    X(MapType_798, 798) \
    X(MapType_799, 799) \
    X(MapType_800, 800) \
    X(MapType_801, 801) \
    X(MapType_802, 802) \
    X(MapType_803, 803) \
    X(MapType_804, 804) \
    X(MapType_805, 805) \
    X(MapId_TheUnderworldSomethingWickedThisWayComes, 806) \
    X(MapId_TheUnderworldDontFearTheReapers, 807) \
    X(MapId_LionsArchHalloweenOutpost, 808) \
    X(MapId_LionsArchWintersdayOutpost, 809) \
    X(MapId_LionsArchCanthanNewYearOutpost, 810) \
    X(MapId_AscalonCityWintersdayOutpost, 811) \
    X(MapId_DroknarsForgeHalloweenOutpost, 812) \
    X(MapId_DroknarsForgeWintersdayOutpost, 813) \
    X(MapId_TombOfThePrimevalKingsHalloweenOutpost, 814) \
    X(MapId_ShingJeaMonasteryDragonFestivalOutpost, 815) \
    X(MapId_ShingJeaMonasteryCanthanNewYearOutpost, 816) \
    X(MapId_KainengCenterCanthanNewYearOutpost, 817) \
    X(MapId_KamadanJewelOfIstanHalloweenOutpost, 818) \
    X(MapId_KamadanJewelOfIstanWintersdayOutpost, 819) \
    X(MapId_KamadanJewelOfIstanCanthanNewYearOutpost, 820) \
    X(MapId_EyeOfTheNorthOutpostWintersdayOutpost, 821) \
    X(MapType_822, 822) \
    X(MapType_823, 823) \
    X(MapType_824, 824) \
    X(MapType_825, 825) \
    X(MapType_826, 826) \
    X(MapType_827, 827) \
    X(MapType_828, 828) \
    X(MapType_829, 829) \
    X(MapType_830, 830) \
    X(MapType_831, 831) \
    X(MapType_832, 832) \
    X(MapType_833, 833) \
    X(MapType_834, 834) \
    X(MapType_835, 835) \
    X(MapType_836, 836) \
    X(MapId_WarInKrytaTalmarkWilderness, 837) \
    X(MapId_WarInKrytaTrialOfZinn, 838) \
    X(MapId_WarInKrytaDivinityCoast, 839) \
    X(MapId_WarInKrytaLionsArchKeep, 840) \
    X(MapId_WarInKrytaDAlessioSeaboard, 841) \
    X(MapId_WarInKrytaTheBattleForLionsArch, 842) \
    X(MapId_WarInKrytaRiversideProvince, 843) \
    X(MapId_WarInKrytaLionsArch, 844) \
    X(MapId_WarInKrytaTheMausoleum, 845) \
    X(MapId_WarInKrytaRise, 846) \
    X(MapId_WarInKrytaShadowsInTheJungle, 847) \
    X(MapId_WarInKrytaAVengeanceOfBlades, 848) \
    X(MapId_WarInKrytaAuspiciousBeginnings, 849) \
    X(MapType_850, 850) \
    X(MapType_851, 851) \
    X(MapType_852, 852) \
    X(MapType_853, 853) \
    X(MapId_OlafsteadCinematic, 854) \
    X(MapId_TheGreatSnowballFightOfTheGodsOperationCrushSpirits, 855) \
    X(MapId_TheGreatSnowballFightOfTheGodsFightingInAWinterWonderland, 856) \
    X(MapId_EmbarkBeach, 857) \
    X(MapType_858, 858) \
    X(MapType_859, 859) \
    X(MapId_DragonsThroatAreaWhatWaitsInShadow, 860) \
    X(MapId_KainengCenterWindsOfChangeAChanceEncounter, 861) \
    X(MapId_TheMarketplaceAreaTrackingTheCorruption, 862) \
    X(MapId_BukdekBywayWindsOfChangeCanthaCourierCrisis, 863) \
    X(MapId_TsumeiVillageWindsOfChangeATreatysATreaty, 864) \
    X(MapId_SeitungHarborAreaDeadlyCargo, 865) \
    X(MapId_TahnnakaiTempleWindsOfChangeTheRescueAttempt, 866) \
    X(MapId_WajjunBazaarWindsOfChangeViolenceInTheStreets, 867) \
    X(MapId_ScarredPsycheMission, 868) \
    X(MapId_ShadowsPassageWindsOfChangeCallingAllThugs, 869) \
    X(MapId_AltrummRuinsFindingJinnai, 870) \
    X(MapId_ShingJeaMonasteryRaidOnShingJeaMonastery, 871) \
    X(MapId_KainengCenterWindsOfChangeRaidOnKainengCenter, 872) \
    X(MapId_WajjunBazaarWindsOfChangeMinistryOfOppression, 873) \
    X(MapId_TheFinalConfrontation, 874) \
    X(MapId_LakesideCounty1070AE, 875) \
    X(MapId_AshfordCatacombs1070AE, 876) \

typedef enum MapId {
    #define X(name, val) name = val,
    MapIdDefs
    #undef X
    MapId_Count,
} MapId;

const char* MapId_ToString(MapId map_id)
{
    switch (map_id) {
    #define X(name, val) case name: return #name;
    MapIdDefs
    #undef X
    default: abort();
    }
}

int MapId_FromInt(int map_id, MapId *result)
{
    switch (map_id) {
    #define X(name, val) case name: break;
    MapIdDefs
    #undef X
    default:
        return ERR_UNSUCCESSFUL;
    }
    *result = (MapId) map_id;
    return ERR_OK;
}
