#pragma once

#define MapIdDefs \
    X(MapId_None, 0) \
    X(MapId_Gladiators_Arena, 1) \
    X(MapId_DEVTestArena1v1, 2) \
    X(MapId_TestMap, 3) \
    X(MapId_WarriorsIsleOutpost, 4) \
    X(MapId_HuntersIsleOutpost, 5) \
    X(MapId_WizardsIsleOutpost, 6) \
    X(MapId_WarriorsIsle, 7) \
    X(MapId_HuntersIsle, 8) \
    X(MapId_WizardsIsle, 9) \
    X(MapId_BloodstoneFen, 10) \
    X(MapId_TheWilds, 11) \
    X(MapId_AuroraGlade, 12) \
    X(MapId_DiessaLowlands, 13) \
    X(MapId_GatesOfKryta, 14) \
    X(MapId_DAlessioSeaboard, 15) \
    X(MapId_DivinityCoast, 16) \
    X(MapId_TalmarkWilderness, 17) \
    X(MapId_TheBlackCurtain, 18) \
    X(MapId_SanctumCay, 19) \
    X(MapId_DroknarsForgeOutpost, 20) \
    X(MapId_TheFrostGate, 21) \
    X(MapId_IceCavesOfSorrow, 22) \
    X(MapId_ThunderheadKeep, 23) \
    X(MapId_IronMinesOfMoladune, 24) \
    X(MapId_BorlisPass, 25) \
    X(MapId_TalusChute, 26) \
    X(MapId_GriffonsMouth, 27) \
    X(MapId_TheGreatNorthernWall, 28) \
    X(MapId_FortRanik, 29) \
    X(MapId_RuinsOfSurmia, 30) \
    X(MapId_XaquangSkyway, 31) \
    X(MapId_NolaniAcademy, 32) \
    X(MapId_OldAscalon, 33) \
    X(MapId_TheFissureOfWoe, 34) \
    X(MapId_EmberLightCampOutpost, 35) \
    X(MapId_GrendichCourthouseOutpost, 36) \
    X(MapId_GlintsChallengeMission, 37) \
    X(MapId_AuguryRockOutpost, 38) \
    X(MapId_SardelacSanitariumOutpost, 39) \
    X(MapId_PikenSquareOutpost, 40) \
    X(MapId_SageLands, 41) \
    X(MapId_MamnoonLagoon, 42) \
    X(MapId_Silverwood, 43) \
    X(MapId_EttinsBack, 44) \
    X(MapId_ReedBog, 45) \
    X(MapId_TheFalls, 46) \
    X(MapId_DryTop, 47) \
    X(MapId_TangleRoot, 48) \
    X(MapId_HengeOfDenraviOutpost, 49) \
    X(MapId_SenjisCornerOutpost, 50) \
    X(MapId_BurningIsleOutpost, 51) \
    X(MapId_TearsOfTheFallen, 52) \
    X(MapId_ScoundrelsRise, 53) \
    X(MapId_LionsArchOutpost, 54) \
    X(MapId_CursedLands, 55) \
    X(MapId_BergenHotSpringsOutpost, 56) \
    X(MapId_NorthKrytaProvince, 57) \
    X(MapId_NeboTerrace, 58) \
    X(MapId_MajestysRest, 59) \
    X(MapId_TwinSerpentLakes, 60) \
    X(MapId_WatchtowerCoast, 61) \
    X(MapId_StingrayStrand, 62) \
    X(MapId_KessexPeak, 63) \
    X(MapId_DAlessioArenaMission, 64) \
    X(MapId_BurningIsle, 65) \
    X(MapId_FrozenIsle, 66) \
    X(MapId_NomadsIsle, 67) \
    X(MapId_DruidsIsle, 68) \
    X(MapId_IsleOfTheDeadGuildHall, 69) \
    X(MapId_TheUnderworld, 70) \
    X(MapId_RiversideProvince, 71) \
    X(MapId_TheHallOfHeroesArenaMission, 72) \
    X(MapId_BrokenTowerMission, 73) \
    X(MapId_HouseZuHeltzerOutpost, 74) \
    X(MapId_TheCourtyardArenaMission, 75) \
    X(MapId_UnholyTemplesMission, 76) \
    X(MapId_BurialMoundsMission, 77) \
    X(MapId_AscalonCityOutpost, 78) \
    X(MapId_TombOfThePrimevalKings, 79) \
    X(MapId_TheVaultMission, 80) \
    X(MapId_TheUnderworldArenaMission, 81) \
    X(MapId_AscalonArena, 82) \
    X(MapId_SacredTemplesMission, 83) \
    X(MapId_Icedome, 84) \
    X(MapId_IronHorseMine, 85) \
    X(MapId_AnvilRock, 86) \
    X(MapId_LornarsPass, 87) \
    X(MapId_SnakeDance, 88) \
    X(MapId_TascasDemise, 89) \
    X(MapId_SpearheadPeak, 90) \
    X(MapId_IceFloe, 91) \
    X(MapId_WitmansFolly, 92) \
    X(MapId_MineralSprings, 93) \
    X(MapId_DreadnoughtsDrift, 94) \
    X(MapId_FrozenForest, 95) \
    X(MapId_TravelersVale, 96) \
    X(MapId_DeldrimorBowl, 97) \
    X(MapId_RegentValley, 98) \
    X(MapId_TheBreach, 99) \
    X(MapId_AscalonFoothills, 100) \
    X(MapId_PockmarkFlats, 101) \
    X(MapId_DragonsGullet, 102) \
    X(MapId_FlameTempleCorridor, 103) \
    X(MapId_EasternFrontier, 104) \
    X(MapId_TheScar, 105) \
    X(MapId_TheAmnoonOasisOutpost, 106) \
    X(MapId_DivinersAscent, 107) \
    X(MapId_VultureDrifts, 108) \
    X(MapId_TheAridSea, 109) \
    X(MapId_ProphetsPath, 110) \
    X(MapId_SaltFlats, 111) \
    X(MapId_SkywardReach, 112) \
    X(MapId_DunesOfDespair, 113) \
    X(MapId_ThirstyRiver, 114) \
    X(MapId_ElonaReach, 115) \
    X(MapId_AuguryRockMission, 116) \
    X(MapId_TheDragonsLair, 117) \
    X(MapId_PerditionRock, 118) \
    X(MapId_RingOfFire, 119) \
    X(MapId_AbaddonsMouth, 120) \
    X(MapId_HellsPrecipice, 121) \
    X(MapId_TitansTears, 122) \
    X(MapId_GoldenGatesMission, 123) \
    X(MapId_ScarredEarth2, 124) \
    X(MapId_TheEternalGrove, 125) \
    X(MapId_LutgardisConservatoryOutpost, 126) \
    X(MapId_VasburgArmoryOutpost, 127) \
    X(MapId_SerenityTempleOutpost, 128) \
    X(MapId_IceToothCaveOutpost, 129) \
    X(MapId_BeaconsPerchOutpost, 130) \
    X(MapId_YaksBendOutpost, 131) \
    X(MapId_FrontierGateOutpost, 132) \
    X(MapId_BeetletunOutpost, 133) \
    X(MapId_FishermensHavenOutpost, 134) \
    X(MapId_TempleOfTheAges, 135) \
    X(MapId_VentarisRefugeOutpost, 136) \
    X(MapId_DruidsOverlookOutpost, 137) \
    X(MapId_MaguumaStadeOutpost, 138) \
    X(MapId_QuarrelFallsOutpost, 139) \
    X(MapId_GyalaHatchery, 140) \
    X(MapId_TheCatacombs, 141) \
    X(MapId_LakesideCounty, 142) \
    X(MapId_TheNorthlands, 143) \
    X(MapId_AscalonCityPreSearing, 144) \
    X(MapId_AscalonAcademy, 145) \
    X(MapId_AscalonAcademyPvPBattleMission, 146) \
    X(MapId_AscalonAcademyUnk, 147) \
    X(MapId_HeroesAudienceOutpost, 148) \
    X(MapId_SeekersPassageOutpost, 149) \
    X(MapId_DestinysGorgeOutpost, 150) \
    X(MapId_CampRankorOutpost, 151) \
    X(MapId_TheGraniteCitadelOutpost, 152) \
    X(MapId_MarhansGrottoOutpost, 153) \
    X(MapId_PortSledgeOutpost, 154) \
    X(MapId_CopperhammerMinesOutpost, 155) \
    X(MapId_GreenHillsCounty, 156) \
    X(MapId_WizardsFolly, 157) \
    X(MapId_RegentValleyPreSearing, 158) \
    X(MapId_TheBarradinEstateOutpost, 159) \
    X(MapId_AshfordAbbeyOutpost, 160) \
    X(MapId_FoiblesFairOutpost, 161) \
    X(MapId_FortRanikPreSearingOutpost, 162) \
    X(MapId_BurningIsleMission, 163) \
    X(MapId_DruidsIsleMission, 164) \
    X(MapId_FrozenIsleMission, 165) \
    X(MapId_WarriorsIsleMission, 166) \
    X(MapId_HuntersIsleMission, 167) \
    X(MapId_WizardsIsleMission, 168) \
    X(MapId_NomadsIsleMission, 169) \
    X(MapId_IsleOfTheDeadGuildHallMission, 170) \
    X(MapId_FrozenIsleOutpost, 171) \
    X(MapId_NomadsIsleOutpost, 172) \
    X(MapId_DruidsIsleOutpost, 173) \
    X(MapId_IsleOfTheDeadGuildHallOutpost, 174) \
    X(MapId_FortKogaMission, 175) \
    X(MapId_ShiverpeakArena, 176) \
    X(MapId_AmnoonArenaMission, 177) \
    X(MapId_DeldrimorArenaMission, 178) \
    X(MapId_TheCragMission, 179) \
    X(MapId_RandomArenasOutpost, 180) \
    X(MapId_TeamArenasOutpost, 181) \
    X(MapId_SorrowsFurnace, 182) \
    X(MapId_GrenthsFootprint, 183) \
    X(MapId_CavalonOutpost, 184) \
    X(MapId_KainengCenterOutpost, 185) \
    X(MapId_DrazachThicket, 186) \
    X(MapId_JayaBluffs, 187) \
    X(MapId_ShenzunTunnels, 188) \
    X(MapId_Archipelagos, 189) \
    X(MapId_MaishangHills, 190) \
    X(MapId_MountQinkai, 191) \
    X(MapId_MelandrusHope, 192) \
    X(MapId_RheasCrater, 193) \
    X(MapId_SilentSurf, 194) \
    X(MapId_UnwakingWatersMission, 195) \
    X(MapId_MorostavTrail, 196) \
    X(MapId_DeldrimorWarCampOutpost, 197) \
    X(MapId_HeroesCryptMission, 198) \
    X(MapId_MourningVeilFalls, 199) \
    X(MapId_Ferndale, 200) \
    X(MapId_PongmeiValley, 201) \
    X(MapId_MonasteryOverlook1, 202) \
    X(MapId_ZenDaijunOutpostMission, 203) \
    X(MapId_MinisterChosEstateOutpostMission, 204) \
    X(MapId_VizunahSquareMission, 205) \
    X(MapId_NahpuiQuarterOutpostMission, 206) \
    X(MapId_TahnnakaiTempleOutpostMission, 207) \
    X(MapId_ArborstoneOutpostMission, 208) \
    X(MapId_BoreasSeabedOutpostMission, 209) \
    X(MapId_SunjiangDistrictOutpostMission, 210) \
    X(MapId_FortAspenwoodMission, 211) \
    X(MapId_TheEternalGroveOutpostMission, 212) \
    X(MapId_TheJadeQuarryMission, 213) \
    X(MapId_GyalaHatcheryOutpostMission, 214) \
    X(MapId_RaisuPalaceOutpostMission, 215) \
    X(MapId_ImperialSanctumOutpostMission, 216) \
    X(MapId_UnwakingWaters, 217) \
    X(MapId_GrenzFrontierMission, 218) \
    X(MapId_AmatzBasin, 219) \
    X(MapId_ShadowsPassage, 220) \
    X(MapId_RaisuPalace, 221) \
    X(MapId_TheAuriosMines, 222) \
    X(MapId_PanjiangPeninsula, 223) \
    X(MapId_KinyaProvince, 224) \
    X(MapId_HaijuLagoon, 225) \
    X(MapId_SunquaVale, 226) \
    X(MapId_WajjunBazaar, 227) \
    X(MapId_BukdekByway, 228) \
    X(MapId_TheUndercity, 229) \
    X(MapId_ShingJeaMonasteryOutpost, 230) \
    X(MapId_ShingJeaArena, 231) \
    X(MapId_ArborstoneExplorable, 232) \
    X(MapId_MinisterChosEstateExplorable, 233) \
    X(MapId_ZenDaijunExplorable, 234) \
    X(MapId_BoreasSeabedExplorable, 235) \
    X(MapId_GreatTempleOfBalthazarOutpost, 236) \
    X(MapId_TsumeiVillageOutpost, 237) \
    X(MapId_SeitungHarborOutpost, 238) \
    X(MapId_RanMusuGardensOutpost, 239) \
    X(MapId_LinnokCourtyard, 240) \
    X(MapId_DwaynaVsGrenth, 241) \
    X(MapId_SunjiangDistrictExplorable, 242) \
    X(MapId_NahpuiQuarterExplorable, 243) \
    X(MapId_UrgozsWarren, 244) \
    X(MapId_TahnnakaiTempleExplorable, 245) \
    X(MapId_AltrummRuins, 246) \
    X(MapId_ZosShivrosChannel, 247) \
    X(MapId_DragonsThroat, 248) \
    X(MapId_IsleOfWeepingStoneOutpost, 249) \
    X(MapId_IsleOfJadeOutpost, 250) \
    X(MapId_HarvestTempleOutpost, 251) \
    X(MapId_BreakerHollowOutpost, 252) \
    X(MapId_LeviathanPitsOutpost, 253) \
    X(MapId_IsleOfTheNameless, 254) \
    X(MapId_ZaishenChallengeOutpost, 255) \
    X(MapId_ZaishenEliteOutpost, 256) \
    X(MapId_MaatuKeepOutpost, 257) \
    X(MapId_ZinKuCorridorOutpost, 258) \
    X(MapId_MonasteryOverlook2, 259) \
    X(MapId_BrauerAcademyOutpost, 260) \
    X(MapId_DurheimArchivesOutpost, 261) \
    X(MapId_BaiPaasuReachOutpost, 262) \
    X(MapId_SeafarersRestOutpost, 263) \
    X(MapId_BejunkanPier, 264) \
    X(MapId_VizunahSquareLocalQuarterOutpost, 265) \
    X(MapId_VizunahSquareForeignQuarterOutpost, 266) \
    X(MapId_FortAspenwoodLuxonOutpost, 267) \
    X(MapId_FortAspenwoodKurzickOutpost, 268) \
    X(MapId_TheJadeQuarryLuxonOutpost, 269) \
    X(MapId_TheJadeQuarryKurzickOutpost, 270) \
    X(MapId_UnwakingWatersLuxonOutpost, 271) \
    X(MapId_UnwakingWatersKurzickOutpost, 272) \
    X(MapId_EtnaranKeysMission, 273) \
    X(MapId_RaisuPavilion, 274) \
    X(MapId_KainengDocks, 275) \
    X(MapId_TheMarketplaceOutpost, 276) \
    X(MapId_TheDeep, 277) \
    X(MapId_AscalonArenaMission, 278) \
    X(MapId_AnnihilationMission, 279) \
    X(MapId_KillCountTrainingMission, 280) \
    X(MapId_PriestAnnihilationTraining, 281) \
    X(MapId_ObeliskAnnihilationTrainingMission, 282) \
    X(MapId_SaoshangTrail, 283) \
    X(MapId_ShiverpeakArenaMission, 284) \
    X(MapId_DAlessioArenaMission3, 285) \
    X(MapId_AmnoonArenaMission3, 286) \
    X(MapId_FortKogaMission3, 287) \
    X(MapId_HeroesCryptMission3, 288) \
    X(MapId_ShiverpeakArenaMission3, 289) \
    X(MapId_SaltsprayBeachLuxonOutpost, 290) \
    X(MapId_SaltsprayBeachKurzickOutpost, 291) \
    X(MapId_HeroesAscentOutpost, 292) \
    X(MapId_GrenzFrontierLuxonOutpost, 293) \
    X(MapId_GrenzFrontierKurzickOutpost, 294) \
    X(MapId_TheAncestralLandsLuxonOutpost, 295) \
    X(MapId_TheAncestralLandsKurzickOutpost, 296) \
    X(MapId_EtnaranKeysLuxonOutpost, 297) \
    X(MapId_EtnaranKeysKurzickOutpost, 298) \
    X(MapId_KaanaiCanyonLuxonOutpost, 299) \
    X(MapId_KaanaiCanyonKurzickOutpost, 300) \
    X(MapId_DAlessioArenaMission2, 301) \
    X(MapId_AmnoonArenaMission2, 302) \
    X(MapId_FortKogaMission2, 303) \
    X(MapId_HeroesCryptMission2, 304) \
    X(MapId_ShiverpeakArenaMission2, 305) \
    X(MapId_TheHallOfHeroes, 306) \
    X(MapId_TheCourtyard, 307) \
    X(MapId_ScarredEarth, 308) \
    X(MapId_TheUnderworldPvP, 309) \
    X(MapId_TanglewoodCopseOutpost, 310) \
    X(MapId_SaintAnjekasShrineOutpost, 311) \
    X(MapId_EredonTerraceOutpost, 312) \
    X(MapId_DivinePath, 313) \
    X(MapId_BrawlersPitMission, 314) \
    X(MapId_PetrifiedArenaMission, 315) \
    X(MapId_SeabedArenaMission, 316) \
    X(MapId_IsleOfWeepingStoneMission, 317) \
    X(MapId_IsleOfJadeMission, 318) \
    X(MapId_ImperialIsleMission, 319) \
    X(MapId_IsleOfMeditationMission, 320) \
    X(MapId_ImperialIsleOutpost, 321) \
    X(MapId_IsleOfMeditationOutpost, 322) \
    X(MapId_IsleOfWeepingStone, 323) \
    X(MapId_IsleOfJade, 324) \
    X(MapId_ImperialIsle, 325) \
    X(MapId_IsleOfMeditation, 326) \
    X(MapId_ShingJeaArenaMission, 327) \
    X(MapId_DragonArena, 328) \
    X(MapId_JahaiBluffs, 329) \
    X(MapId_KamadanMission, 330) \
    X(MapId_MargaCoast, 331) \
    X(MapId_FahranurMission, 332) \
    X(MapId_SunwardMarches, 333) \
    X(MapId_BarbarousShore, 334) \
    X(MapId_CampHojanuOutpost, 335) \
    X(MapId_BahdokCaverns, 336) \
    X(MapId_WehhanTerracesOutpost, 337) \
    X(MapId_DejarinEstate, 338) \
    X(MapId_ArkjokWard, 339) \
    X(MapId_YohlonHavenOutpost, 340) \
    X(MapId_GandaraTheMoonFortress, 341) \
    X(MapId_TheFloodplainOfMahnkelon, 342) \
    X(MapId_LionsArchSunspearsInKryta, 343) \
    X(MapId_TuraisProcession, 344) \
    X(MapId_SunspearSanctuaryOutpost, 345) \
    X(MapId_AspenwoodGateKurzickOutpost, 346) \
    X(MapId_AspenwoodGateLuxonOutpost, 347) \
    X(MapId_JadeFlatsKurzickOutpost, 348) \
    X(MapId_JadeFlatsLuxonOutpost, 349) \
    X(MapId_YatendiCanyons, 350) \
    X(MapId_ChantryOfSecretsOutpost, 351) \
    X(MapId_GardenOfSeborhin, 352) \
    X(MapId_HoldingsOfChokhin, 353) \
    X(MapId_MihanuTownshipOutpost, 354) \
    X(MapId_VehjinMines, 355) \
    X(MapId_BasaltGrottoOutpost, 356) \
    X(MapId_ForumHighlands, 357) \
    X(MapId_KainengCenterSunspearsInCantha, 358) \
    X(MapId_ResplendentMakuun, 359) \
    X(MapId_HonurHillOutpost, 360) \
    X(MapId_WildernessOfBahdza, 361) \
    X(MapId_VehtendiValley, 362) \
    X(MapId_YahnurMarketOutpost, 363) \
    X(MapId_TheHiddenCityOfAhdashim, 364) \
    X(MapId_TheKodashBazaarOutpost, 365) \
    X(MapId_LionsGate, 366) \
    X(MapId_TheMirrorOfLyss, 367) \
    X(MapId_SecureTheRefuge, 368) \
    X(MapId_VentaCemetery, 369) \
    X(MapId_KamadanJewelOfIstanExplorable, 370) \
    X(MapId_TheTribunal, 371) \
    X(MapId_KodonurCrossroads, 372) \
    X(MapId_RilohnRefuge, 373) \
    X(MapId_PogahnPassage, 374) \
    X(MapId_ModdokCrevice, 375) \
    X(MapId_TiharkOrchard, 376) \
    X(MapId_Consulate, 377) \
    X(MapId_PlainsOfJarin, 378) \
    X(MapId_SunspearGreatHallOutpost, 379) \
    X(MapId_CliffsOfDohjok, 380) \
    X(MapId_DzagonurBastion, 381) \
    X(MapId_DashaVestibule, 382) \
    X(MapId_GrandCourtOfSebelkeh, 383) \
    X(MapId_CommandPost, 384) \
    X(MapId_JokosDomain, 385) \
    X(MapId_BonePalaceOutpost, 386) \
    X(MapId_TheRupturedHeart, 387) \
    X(MapId_TheMouthOfTormentOutpost, 388) \
    X(MapId_TheShatteredRavines, 389) \
    X(MapId_LairOfTheForgottenOutpost, 390) \
    X(MapId_PoisonedOutcrops, 391) \
    X(MapId_TheSulfurousWastes, 392) \
    X(MapId_TheEbonyCitadelOfMallyxMission, 393) \
    X(MapId_TheAlkaliPan, 394) \
    X(MapId_ALandOfHeroes, 395) \
    X(MapId_CrystalOverlook, 396) \
    X(MapId_KamadanJewelOfIstanOutpost, 397) \
    X(MapId_GateOfTormentOutpost, 398) \
    X(MapId_NightfallenGarden, 399) \
    X(MapId_ChurrhirFields, 400) \
    X(MapId_BeknurHarborOutpost, 401) \
    X(MapId_TheUnderworld2, 402) \
    X(MapId_HeartOfAbaddon, 403) \
    X(MapId_TheUnderworld3, 404) \
    X(MapId_NightfallenCoast, 405) \
    X(MapId_NightfallenJahai, 406) \
    X(MapId_DepthsOfMadness, 407) \
    X(MapId_RollerbeetleRacing, 408) \
    X(MapId_DomainOfFear, 409) \
    X(MapId_GateOfFearOutpost, 410) \
    X(MapId_DomainOfPain, 411) \
    X(MapId_BloodstoneFenQuest, 412) \
    X(MapId_DomainOfSecrets, 413) \
    X(MapId_GateOfSecretsOutpost, 414) \
    X(MapId_DomainOfAnguish, 415) \
    X(MapId_OozePitMission, 416) \
    X(MapId_JennursHorde, 417) \
    X(MapId_NunduBay, 418) \
    X(MapId_GateOfDesolation, 419) \
    X(MapId_ChampionsDawnOutpost, 420) \
    X(MapId_RuinsOfMorah, 421) \
    X(MapId_FahranurTheFirstCity, 422) \
    X(MapId_BjoraMarches, 423) \
    X(MapId_ZehlonReach, 424) \
    X(MapId_LahtendaBog, 425) \
    X(MapId_ArborBay, 426) \
    X(MapId_IssnurIsles, 427) \
    X(MapId_BeknurHarbor, 428) \
    X(MapId_MehtaniKeys, 429) \
    X(MapId_KodlonuHamletOutpost, 430) \
    X(MapId_IslandOfShehkah, 431) \
    X(MapId_JokanurDiggings, 432) \
    X(MapId_BlacktideDen, 433) \
    X(MapId_ConsulateDocks, 434) \
    X(MapId_GateOfPain, 435) \
    X(MapId_GateOfMadness, 436) \
    X(MapId_AbaddonsGate, 437) \
    X(MapId_SunspearArena, 438) \
    X(MapId_IceCliffChasms, 439) \
    X(MapId_BokkaAmphitheatre, 440) \
    X(MapId_RivenEarth, 441) \
    X(MapId_TheAstralariumOutpost, 442) \
    X(MapId_ThroneOfSecrets, 443) \
    X(MapId_ChurranuIslandArenaMission, 444) \
    X(MapId_ShingJeaMonasteryMission, 445) \
    X(MapId_HaijuLagoonMission, 446) \
    X(MapId_JayaBluffsMission, 447) \
    X(MapId_SeitungHarborMission, 448) \
    X(MapId_TsumeiVillageMission, 449) \
    X(MapId_SeitungHarborMission2, 450) \
    X(MapId_TsumeiVillageMission2, 451) \
    X(MapId_DrakkarLake, 452) \
    X(MapId_MinisterChosEstateMission2, 453) \
    X(MapId_UnchartedIsleOutpost, 454) \
    X(MapId_IsleOfWurmsOutpost, 455) \
    X(MapId_UnchartedIsle, 456) \
    X(MapId_IsleOfWurms, 457) \
    X(MapId_UnchartedIsleMission, 458) \
    X(MapId_IsleOfWurmsMission, 459) \
    X(MapId_SunspearArenaMission, 460) \
    X(MapId_CorruptedIsleOutpost, 461) \
    X(MapId_IsleOfSolitudeOutpost, 462) \
    X(MapId_CorruptedIsle, 463) \
    X(MapId_IsleOfSolitude, 464) \
    X(MapId_CorruptedIsleMission, 465) \
    X(MapId_IsleOfSolitudeMission, 466) \
    X(MapId_SunDocks, 467) \
    X(MapId_ChahbekVillage, 468) \
    X(MapId_RemainsOfSahlahja, 469) \
    X(MapId_JagaMoraine, 470) \
    X(MapId_BombardmentMission, 471) \
    X(MapId_NorrhartDomains, 472) \
    X(MapId_HeroBattlesOutpost, 473) \
    X(MapId_TheBeachheadMission, 474) \
    X(MapId_TheCrossingMission, 475) \
    X(MapId_DesertSandsMission, 476) \
    X(MapId_VarajarFells, 477) \
    X(MapId_DajkahInlet, 478) \
    X(MapId_TheShadowNexus, 479) \
    X(MapId_SparkflySwamp, 480) \
    X(MapId_GateOfTheNightfallenLandsOutpost, 481) \
    X(MapId_CathedralOfFlamesLevel1, 482) \
    X(MapId_TheTroubledKeeper, 483) \
    X(MapId_VerdantCascades, 484) \
    X(MapId_CathedralOfFlamesLevel2, 485) \
    X(MapId_CathedralOfFlamesLevel3, 486) \
    X(MapId_MagusStones, 487) \
    X(MapId_CatacombsOfKathandraxLevel1, 488) \
    X(MapId_CatacombsOfKathandraxLevel2, 489) \
    X(MapId_AlcaziaTangle, 490) \
    X(MapId_RragarsMenagerieLevel1, 491) \
    X(MapId_RragarsMenagerieLevel2, 492) \
    X(MapId_RragarsMenagerieLevel3, 493) \
    X(MapId_OozePit, 494) \
    X(MapId_SlaversExileLevel1, 495) \
    X(MapId_OolasLabLevel1, 496) \
    X(MapId_OolasLabLevel2, 497) \
    X(MapId_OolasLabLevel3, 498) \
    X(MapId_ShardsOfOrrLevel1, 499) \
    X(MapId_ShardsOfOrrLevel2, 500) \
    X(MapId_ShardsOfOrrLevel3, 501) \
    X(MapId_ArachnisHauntLevel1, 502) \
    X(MapId_ArachnisHauntLevel2, 503) \
    X(MapId_FetidRiverMission, 504) \
    X(MapId_ForgottenShrinesMission, 505) \
    X(MapId_AntechamberMission, 506) \
    X(MapId_VloxenExcavationsLevel1, 507) \
    X(MapId_VloxenExcavationsLevel2, 508) \
    X(MapId_VloxenExcavationsLevel3, 509) \
    X(MapId_HeartOfTheShiverpeaksLevel1, 510) \
    X(MapId_HeartOfTheShiverpeaksLevel2, 511) \
    X(MapId_HeartOfTheShiverpeaksLevel3, 512) \
    X(MapId_BloodstoneCavesLevel1, 513) \
    X(MapId_BloodstoneCavesLevel2, 514) \
    X(MapId_BloodstoneCavesLevel3, 515) \
    X(MapId_BogrootGrowthsLevel1, 516) \
    X(MapId_BogrootGrowthsLevel2, 517) \
    X(MapId_RavensPointLevel1, 518) \
    X(MapId_RavensPointLevel2, 519) \
    X(MapId_RavensPointLevel3, 520) \
    X(MapId_SlaversExileLevel2, 521) \
    X(MapId_SlaversExileLevel3, 522) \
    X(MapId_SlaversExileLevel4, 523) \
    X(MapId_SlaversExileLevel5, 524) \
    X(MapId_VloxsFalls, 525) \
    X(MapId_BattledepthsLevel1, 526) \
    X(MapId_BattledepthsLevel2, 527) \
    X(MapId_BattledepthsLevel3, 528) \
    X(MapId_SepulchreOfDragrimmarLevel1, 529) \
    X(MapId_SepulchreOfDragrimmarLevel2, 530) \
    X(MapId_FrostmawsBurrowsLevel1, 531) \
    X(MapId_FrostmawsBurrowsLevel2, 532) \
    X(MapId_FrostmawsBurrowsLevel3, 533) \
    X(MapId_FrostmawsBurrowsLevel4, 534) \
    X(MapId_FrostmawsBurrowsLevel5, 535) \
    X(MapId_DarkrimeDelvesLevel1, 536) \
    X(MapId_DarkrimeDelvesLevel2, 537) \
    X(MapId_DarkrimeDelvesLevel3, 538) \
    X(MapId_GaddsEncampmentOutpost, 539) \
    X(MapId_UmbralGrottoOutpost, 540) \
    X(MapId_RataSumOutpost, 541) \
    X(MapId_TarnishedHavenOutpost, 542) \
    X(MapId_EyeOfTheNorthOutpost, 543) \
    X(MapId_SifhallaOutpost, 544) \
    X(MapId_GunnarsHoldOutpost, 545) \
    X(MapId_OlafsteadOutpost, 546) \
    X(MapId_HallOfMonuments, 547) \
    X(MapId_DaladaUplands, 548) \
    X(MapId_DoomloreShrineOutpost, 549) \
    X(MapId_GrothmarWardowns, 550) \
    X(MapId_LongeyesLedgeOutpost, 551) \
    X(MapId_SacnothValley, 552) \
    X(MapId_CentralTransferChamberOutpost, 553) \
    X(MapId_CurseOfTheNornbear, 554) \
    X(MapId_BloodWashesBlood, 555) \
    X(MapId_AGateTooFarLevel1, 556) \
    X(MapId_AGateTooFarLevel2, 557) \
    X(MapId_AGateTooFarLevel3, 558) \
    X(MapId_TheElusiveGolemancerLevel1, 559) \
    X(MapId_TheElusiveGolemancerLevel2, 560) \
    X(MapId_TheElusiveGolemancerLevel3, 561) \
    X(MapId_FindingTheBloodstoneLevel1, 562) \
    X(MapId_FindingTheBloodstoneLevel2, 563) \
    X(MapId_FindingTheBloodstoneLevel3, 564) \
    X(MapId_GeniusOperatedLivingEnchantedManifestation, 565) \
    X(MapId_AgainstTheCharr, 566) \
    X(MapId_WarbandOfBrothersLevel1, 567) \
    X(MapId_WarbandOfBrothersLevel2, 568) \
    X(MapId_WarbandOfBrothersLevel3, 569) \
    X(MapId_AssaultOnTheStronghold, 570) \
    X(MapId_DestructionsDepthsLevel1, 571) \
    X(MapId_DestructionsDepthsLevel2, 572) \
    X(MapId_DestructionsDepthsLevel3, 573) \
    X(MapId_ATimeForHeroes, 574) \
    X(MapId_WarbandTraining, 575) \
    X(MapId_BorealStationOutpost, 576) \
    X(MapId_CatacombsOfKathandraxLevel3, 577) \
    X(MapId_AttackOfTheNornbear, 578) \
    X(MapId_CinematicCaveNornCursed, 579) \
    X(MapId_CinematicSteppeInterrogation, 580) \
    X(MapId_CinematicInteriorResearch, 581) \
    X(MapId_CinematicEyeVisionA, 582) \
    X(MapId_CinematicEyeVisionB, 583) \
    X(MapId_CinematicEyeVisionC, 584) \
    X(MapId_CinematicEyeVisionD, 585) \
    X(MapId_PolymockColiseum, 586) \
    X(MapId_PolymockGlacier, 587) \
    X(MapId_PolymockCrossing, 588) \
    X(MapId_CinematicMountainResolution, 589) \
    X(MapId_ColdAsIce, 590) \
    X(MapId_BeneathLionsArch, 591) \
    X(MapId_TunnelsBelowCantha, 592) \
    X(MapId_CavernsBelowKamadan, 593) \
    X(MapId_CinematicMountainDwarfs, 594) \
    X(MapId_ServiceInDefenseOfTheEye, 595) \
    X(MapId_ManoANornO, 596) \
    X(MapId_ServicePracticeDummy, 597) \
    X(MapId_HeroTutorial, 598) \
    X(MapId_TheNornFightingTournament, 599) \
    X(MapId_SecretLairOfTheSnowmen, 600) \
    X(MapId_NornBrawlingChampionship, 601) \
    X(MapId_KilroysPunchoutTraining, 602) \
    X(MapId_FronisIrontoesLairMission, 603) \
    X(MapId_TheJusticiarsEnd, 604) \
    X(MapId_TheGreatNornAlemoot, 605) \
    X(MapId_VarajarFellsUnknown, 606) \
    X(MapId_Epilogue, 607) \
    X(MapId_InsidiousRemnants, 608) \
    X(MapId_AttackOnJalissCamp, 609) \
    X(MapId_CostumeBrawlOutpost, 610) \
    X(MapId_WhitefuryRapidsMission, 611) \
    X(MapId_KystenShoreMission, 612) \
    X(MapId_DeepwayRuinsMission, 613) \
    X(MapId_PlikkupWorksMission, 614) \
    X(MapId_KilroysPunchoutTournament, 615) \
    X(MapId_SpecialOpsFlameTempleCorridor, 616) \
    X(MapId_SpecialOpsDragonsGullet, 617) \
    X(MapId_SpecialOpsGrendichCourthouse, 618) \
    X(MapId_TheTenguAccords, 619) \
    X(MapId_TheBattleOfJahai, 620) \
    X(MapId_TheFlightNorth, 621) \
    X(MapId_TheRiseOfTheWhiteMantle, 622) \
    X(MapId_, 623) \
    X(MapId_FindingTheBloodstoneMission, 624) \
    X(MapId_GeniusOperatedLivingEnchantedManifestationMission, 625) \
    X(MapId_AgainstTheCharrMission, 626) \
    X(MapId_WarbandOfBrothersMission, 627) \
    X(MapId_AssaultOnTheStrongholdMission, 628) \
    X(MapId_DestructionsDepthsMission, 629) \
    X(MapId_ATimeForHeroesMission, 630) \
    X(MapId_CurseOfTheNornbearMission, 631) \
    X(MapId_BloodWashesBloodMission, 632) \
    X(MapId_AGateTooFarMission, 633) \
    X(MapId_TheElusiveGolemancerMission, 634) \
    X(MapId_SecretLairOfTheSnowmen2, 635) \
    X(MapId_SecretLairOfTheSnowmen3, 636) \
    X(MapId_DroknarsForgeCinematic, 637) \
    X(MapId_IsleOfTheNamelessPvP, 638) \
    X(MapId_TempleOfTheAgesROX, 639) \
    X(MapId_WajjunBazaarPOX, 640) \
    X(MapId_BokkaAmphitheatreNOX, 641) \
    X(MapId_SecretUndergroundLair, 642) \
    X(MapId_GolemTutorialSimulation, 643) \
    X(MapId_SnowballDominance, 644) \
    X(MapId_ZaishenMenagerieGrounds, 645) \
    X(MapId_ZaishenMenagerieOutpost, 646) \
    X(MapId_CodexArenaOutpost, 647) \
    X(MapId_TheUnderworldSomethingWickedThisWayComes, 648) \
    X(MapId_TheUnderworldDontFearTheReapers, 649) \
    X(MapId_LionsArchHalloweenOutpost, 650) \
    X(MapId_LionsArchWintersdayOutpost, 651) \
    X(MapId_LionsArchCanthanNewYearOutpost, 652) \
    X(MapId_AscalonCityWintersdayOutpost, 653) \
    X(MapId_DroknarsForgeHalloweenOutpost, 654) \
    X(MapId_DroknarsForgeWintersdayOutpost, 655) \
    X(MapId_TombOfThePrimevalKingsHalloweenOutpost, 656) \
    X(MapId_ShingJeaMonasteryDragonFestivalOutpost, 657) \
    X(MapId_ShingJeaMonasteryCanthanNewYearOutpost, 658) \
    X(MapId_KainengCenterCanthanNewYearOutpost, 659) \
    X(MapId_KamadanJewelOfIstanHalloweenOutpost, 660) \
    X(MapId_KamadanJewelOfIstanWintersdayOutpost, 661) \
    X(MapId_KamadanJewelOfIstanCanthanNewYearOutpost, 662) \
    X(MapId_EyeOfTheNorthOutpostWintersdayOutpost, 663) \
    X(MapId_WarInKrytaTalmarkWilderness, 664) \
    X(MapId_WarInKrytaTrialOfZinn, 665) \
    X(MapId_WarInKrytaDivinityCoast, 666) \
    X(MapId_WarInKrytaLionsArchKeep, 667) \
    X(MapId_WarInKrytaDAlessioSeaboard, 668) \
    X(MapId_WarInKrytaTheBattleForLionsArch, 669) \
    X(MapId_WarInKrytaRiversideProvince, 670) \
    X(MapId_WarInKrytaLionsArch, 671) \
    X(MapId_WarInKrytaTheMausoleum, 672) \
    X(MapId_WarInKrytaRise, 673) \
    X(MapId_WarInKrytaShadowsInTheJungle, 674) \
    X(MapId_WarInKrytaAVengeanceOfBlades, 675) \
    X(MapId_WarInKrytaAuspiciousBeginnings, 676) \
    X(MapId_OlafsteadCinematic, 677) \
    X(MapId_TheGreatSnowballFightOfTheGodsOperationCrushSpirits, 678) \
    X(MapId_TheGreatSnowballFightOfTheGodsFightingInAWinterWonderland, 679) \
    X(MapId_EmbarkBeach, 680) \
    X(MapId_DragonsThroatAreaWhatWaitsInShadow, 681) \
    X(MapId_KainengCenterWindsOfChangeAChanceEncounter, 682) \
    X(MapId_TheMarketplaceAreaTrackingTheCorruption, 683) \
    X(MapId_BukdekBywayWindsOfChangeCanthaCourierCrisis, 684) \
    X(MapId_TsumeiVillageWindsOfChangeATreatysATreaty, 685) \
    X(MapId_SeitungHarborAreaDeadlyCargo, 686) \
    X(MapId_TahnnakaiTempleWindsOfChangeTheRescueAttempt, 687) \
    X(MapId_WajjunBazaarWindsOfChangeViolenceInTheStreets, 688) \
    X(MapId_ScarredPsycheMission, 689) \
    X(MapId_ShadowsPassageWindsOfChangeCallingAllThugs, 690) \
    X(MapId_AltrummRuinsFindingJinnai, 691) \
    X(MapId_ShingJeaMonasteryRaidOnShingJeaMonastery, 692) \
    X(MapId_KainengCenterWindsOfChangeRaidOnKainengCenter, 693) \
    X(MapId_WajjunBazaarWindsOfChangeMinistryOfOppression, 694) \
    X(MapId_TheFinalConfrontation, 695) \
    X(MapId_LakesideCounty1070AE, 696) \
    X(MapId_AshfordCatacombs1070AE, 697) \

typedef enum MapId {
    #define X(name, val) name = val,
    MapIdDefs
    #undef X
    MapId_Count,
} MapId;

const char* MapId_ToString(MapId map_id)
{
    switch (map_id) {
    #define X(name, val) case name: return #name;
    MapIdDefs
    #undef X
    default: abort();
    }
}

int MapId_FromInt(int map_id, MapId *result)
{
    switch (map_id) {
    #define X(name, val) case name: break;
    MapIdDefs
    #undef X
    default:
        return ERR_UNSUCCESSFUL;
    }
    *result = (MapId) map_id;
    return ERR_OK;
}
