item_types = {
    0: 'ItemType_Salvage',
    1: 'ItemType_Leadhand',
    2: 'ItemType_Axe',
    3: 'ItemType_Bag',
    4: 'ItemType_Feet',
    5: 'ItemType_Bow',
    6: 'ItemType_Bundle',
    7: 'ItemType_Chest',
    8: 'ItemType_Rune',
    9: 'ItemType_Consumable',
    10: 'ItemType_Dye',
    11: 'ItemType_Material',
    12: 'ItemType_Focus',
    13: 'ItemType_Arms',
    14: 'ItemType_Sigil',
    15: 'ItemType_Hammer',
    16: 'ItemType_Head',
    17: 'ItemType_SalvageItem',
    18: 'ItemType_Key',
    19: 'ItemType_Legs',
    20: 'ItemType_Coins',
    21: 'ItemType_QuestItem',
    22: 'ItemType_Wand',
    24: 'ItemType_Shield',
    26: 'ItemType_Staff',
    27: 'ItemType_Sword',
    29: 'ItemType_Kit',
    30: 'ItemType_Trophy',
    31: 'ItemType_Scroll',
    32: 'ItemType_Daggers',
    33: 'ItemType_Present',
    34: 'ItemType_Minipet',
    35: 'ItemType_Scythe',
    36: 'ItemType_Spear',
    43: 'ItemType_Handbook',
    44: 'ItemType_CostumeBody',
    45: 'ItemType_CostumeHead',
}

dye_colors = {
    0: 'DyeColor_None',
    2: 'DyeColor_Blue',
    3: 'DyeColor_Green',
    4: 'DyeColor_Purple',
    5: 'DyeColor_Red',
    6: 'DyeColor_Yellow',
    7: 'DyeColor_Brown',
    8: 'DyeColor_Orange',
    9: 'DyeColor_Silver',
    10: 'DyeColor_Black',
    11: 'DyeColor_Gray',
    12: 'DyeColor_White',
    13: 'DyeColor_Pink',
}

professions = {
    0 : 'Profession_None',
    1 : 'Profession_Warrior',
    2 : 'Profession_Ranger',
    3 : 'Profession_Monk',
    4 : 'Profession_Necromancer',
    5 : 'Profession_Mesmer',
    6 : 'Profession_Elementalist',
    7 : 'Profession_Assassin',
    8 : 'Profession_Ritualist',
    9 : 'Profession_Paragon',
    10 : 'Profession_Dervish',
}

campaign_types = {
    0: 'CampaignType_Pvp',
    1: 'CampaignType_Prophecies',
    2: 'CampaignType_Faction',
    3: 'CampaignType_Nightfall',
}
